"""
Write docs/FINDINGS.md from the solver output.

FINDINGS.md used to be written by hand, and its numbers drifted from the
site (Drifter "4.073" in the doc, "15.49" on the page, "53.58" in a table).
Every number below is read from data/optimization.json, data/orders.json and
data/benchmarks.json, so the document cannot disagree with the site.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
STAGES = ["laning", "early", "mid", "late", "full"]
LABEL = {"laning": "6,000", "early": "12,000", "mid": "20,000", "late": "32,000", "full": "50,000"}


def load(name, default=None):
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        return default
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def ranked(overall):
    return sorted(overall.items(), key=lambda kv: -kv[1])


def row(table, stage, hero):
    return next(r for r in table["stages"][stage] if r["hero"] == hero)


def rank_of(table, stage, hero):
    rows = table["stages"][stage]
    score = row(table, stage, hero)["score"]
    return 1 + sum(1 for r in rows if r["score"] > score)


def main():
    O = load("optimization.json")
    orders = load("orders.json", {})
    bench = load("benchmarks.json", {"cases": []})
    tf = O["teamfight"]
    ar = {"stages": O["stages"], "overall": O["overall"]}
    tf_rank, ar_rank = ranked(tf["overall"]), ranked(ar["overall"])
    hero = tf_rank[0][0]
    full, late = row(tf, "full", hero), row(tf, "late", hero)
    model = O["model"]

    out = []
    w = out.append
    w("# Findings — best sustain + damage build for teamfights\n")
    w("*Generated by `scripts/findings.py` from the solver output. Patch baseline: "
      "Minor Update 09-16-2026 (still live on 2026-09-25).*\n")

    w("## Answer\n")
    w(f"**{hero}** is the strongest teamfight sustain + damage pick in the model "
      f"(stage-weighted teamfight score **{tf_rank[0][1]:.3f}**, ahead of "
      f"{tf_rank[1][0]} {tf_rank[1][1]:.3f} and {tf_rank[2][0]} {tf_rank[2][1]:.3f}). "
      f"It ranks #{rank_of(tf, 'late', hero)} at 32k and #{rank_of(tf, 'full', hero)} at 50k.\n")
    w(f"All-round #1 (15% picks, 30% skirmish, 55% teamfight): **{ar_rank[0][0]}** "
      f"({ar_rank[0][1]:.3f}).\n")

    w(f"### {hero} full build ({full['spend']:,} souls, {len(full['items'])}/12 slots)\n")
    w("| # | buy | souls | running |\n|---:|---|---:|---:|")
    for i, s in enumerate(orders.get(f"{hero}|full|teamfight", []), 1):
        name = f"{s['from']} → **{s['item']}**" if s["kind"] == "upgrade" else f"**{s['item']}**"
        w(f"| {i} | {name} | {s['cost']:,} | {s['running']:,} |")
    w("")
    w(f"Ability tiers {'/'.join(map(str, full['ability_levels']))} "
      f"({full['ability_points']} points). Weighted over the teamfight scenarios: "
      f"**{full['total_dps']:.0f} DPS** on target (+{full['cleave_dps']:.0f} splash), "
      f"**{full['heal_ps']:.0f} HP/s** net healing after anti-heal "
      f"({full['sustain_ratio'] * 100:.0f}% of incoming), **{full['ehp']:,.0f} EHP**, "
      f"bullet/spirit resist {full['bullet_resist']:.0f}%/{full['tech_resist']:.0f}%.\n")
    w(f"Late (32k) version: {', '.join(late['items'])}.\n")

    w("### Stage by stage\n")
    w("| stage | souls | teamfight #1 | score | " + hero + " rank | " + hero + " score |")
    w("|---|---:|---|---:|---:|---:|")
    for st in STAGES:
        top = tf["stages"][st][0]
        w(f"| {st} | {LABEL[st]} | {top['hero']} | {top['score']:.3f} | "
          f"#{rank_of(tf, st, hero)} | {row(tf, st, hero)['score']:.3f} |")
    w("")

    w("### Top 10\n")
    w("| # | teamfight | score | all-round | score |\n|---:|---|---:|---|---:|")
    for i in range(10):
        w(f"| {i + 1} | {tf_rank[i][0]} | {tf_rank[i][1]:.3f} | {ar_rank[i][0]} | {ar_rank[i][1]:.3f} |")
    w("")

    sens = load("sensitivity.json")
    if sens:
        wins = sum(1 for h in sens["winners"].values() if h == hero)
        w("### How robust is that?\n")
        w(f"Re-scoring every solved build under alternative values of the three judgment calls "
          f"(fight window 15/20/30 s, healing floor 15/25/40%, splash value 25/50/75%): "
          f"**{hero} is #1 in {wins} of {len(sens['winners'])} variants.**\n")
        w("| hero | baseline rank | best | worst |\n|---|---:|---:|---:|")
        for h, r in sens["top10"].items():
            w(f"| {h} | #{r['baseline_rank']} | #{r['best_rank']} | #{r['worst_rank']} |")
        w("")
        w("Winner per variant: " + ", ".join(f"{n} → {h}" for n, h in sens["winners"].items()) + ".\n")

    for case in bench.get("cases", []):
        g, s, same = case["given"], case["solved"], case["solved_same_spend"]
        w(f"## Benchmark: {case['label']}\n")
        w(case.get("note", "") + "\n")
        w("| build | item souls | teamfight | all-round | TF DPS | TF heal/s | EHP |")
        w("|---|---:|---:|---:|---:|---:|---:|")
        for name, b in (("their build", g), ("solver, same item souls", same),
                        (f"solver, all {case['net_worth']:,}", s)):
            w(f"| {name} | {b['spend']:,} | {b['teamfight']:.3f} | {b['allround']:.3f} | "
              f"{b['tf_dps']:.0f} | {b['tf_heal']:.0f} | {b['ehp']:,.0f} |")
        w("")
        w(f"- Their items: {', '.join(g['items'])}")
        w(f"- Same-souls solve: {', '.join(same['items'])}")
        w(f"- Full-net-worth solve: {', '.join(s['items'])}\n")

    w("## What was wrong before (fixed 2026-09-25)\n")
    for line in (
        "Drifter's rows were hand-overwritten by `apply_all_drifter_fixes.py`: a 16-item build, a 64,000-soul "
        "budget (everyone else 50,000) and one easy scenario instead of the five-scenario ensemble. "
        "`verify/check_outputs.py` failed on the published data.",
        "Slot rules: the game has 12 universal slots (9 + 3 from Walkers); the model used 16 with 4/4/4 + 4 flex.",
        "Drifter-only hacks: a 7 m engagement range for Drifter alone, and Bloodscent's +15/26% isolated-target "
        "amp applied to every target in every teamfight. Isolation now only applies to picks, some skirmishes "
        "and Eternal Night's uptime.",
        "Extractor dropped untyped tooltip sections and `elevated_properties`, so conditional buffs "
        "(Burst Fire +32% fire rate, Stalker, Healing Tempo) were counted as always on.",
        "Escalating Resilience was 51% bullet resist (stacks × 2% × 0.85); the wiki cap is 30%.",
        "Golden Goose Egg's and Cursed Relic's penalty on YOUR damage was treated as a debuff on enemies.",
        "Self-drain (Blood Tribute) was clamped away whenever healing was low.",
        "~25 item damage procs (Mystic Shot, Tesla, Toxic Bullets, Spirit Burn, Torment Pulse, Mercurial "
        "Magnum, …) and enemy debuffs (Juggernaut, Hunter's Aura, Suppressor, Rusted Barrel) were ignored.",
        "The reference opponent's resist shred never applied to you, so resist was overvalued for every hero; "
        "its DPS also omitted procs, bleeds and Siphon.",
        "Healing could cancel 92% of incoming damage (8% floor), which produced 'unkillable' 53× scores. "
        "The floor is now 25%.",
        "Cooldowns were averaged over a whole game (Vampiric Burst 17% uptime, Eternal Night 6%), undervaluing "
        "actives, ultimates and burst kits. Each scenario is now one 20-second engagement entered with every "
        "cooldown ready.",
        "Weapon/Spirit Shielding's 18% resist was permanent; it only lasts the 8 s barrier (05-22-2026 patch).",
        "Mercurial Magnum's per-bullet bonus is '+20% Base Bullet Damage' in the game files, not flat damage; "
        "read as flat it gave fast-firing heroes (Bebop) ~976 DPS and put it in every build.",
        "Ability scale types were ignored: per-boon (Venator's Ira Domini) and melee-scaled (Silver's Boot Kick) "
        "coefficients were multiplied by Spirit Power, and Graves' Spirit Power buff counted as damage.",
        "Early game had 12 slots; you start with 9 and gain one per enemy Walker. Builds and purchase orders now "
        "respect 9 / 10 / 11 / 12 slots by net worth.",
        "The website carried a second JavaScript copy of the model (with the same hacks) and the Heroes and "
        "Items tabs were broken (`renderHero` / `renderItems` did not exist).",
    ):
        w(f"- {line}")
    w("")

    w("## Model\n")
    w("| scenario | all-round weight | teamfight weight | focus | anti-heal | bullet share | isolated |")
    w("|---|---:|---:|---:|---:|---:|---:|")
    for name, sc in model["scenarios"].items():
        w(f"| {name} | {sc['weight'] * 100:.0f}% | {model['objectives']['teamfight'].get(name, 0) * 100:.0f}% | "
          f"{sc['focus']}× | {sc['antiheal']}% | {sc['bullet_frac'] * 100:.0f}% | {sc['isolation'] * 100:.0f}% |")
    w("")
    w(f"Search: {model['optimization']}; reference-opponent drift per pass "
      f"{' → '.join(f'{d * 100:.1f}%' for d in model['reference_drift'])}; "
      f"runtime {model['runtime_s'] / 60:.1f} min. Every build is re-verified as a one-exchange local "
      f"optimum by `verify/check_outputs.py --deep`.\n")
    w("Not modelled: crowd control, mobility, objectives, farming, vision, team composition, "
      "player skill, melee routing and resource-gated abilities. Treat the cross-hero order as a combat "
      "ranking, not a universal tier list.\n")

    path = os.path.join(ROOT, "docs", "FINDINGS.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
